routers:
  R1:
    host: 192.168.67.103
    port: 5000
    vlan_commands:
    - create vlan LCC tag 10
    - configure vlan LCC add port 1 untagged
    - configure vlan LCC ipaddress 10.20.4.1/26
    - create vlan LABARC tag 20
    - configure vlan LABARC add port 2 untagged
    - configure vlan LABARC ipaddress 10.20.4.65/26
    - create vlan LABSPI tag 30
    - configure vlan LABSPI add port 3 untagged
    - configure vlan LABSPI ipaddress 10.20.4.225/28
    - create vlan BB tag 120
    - configure vlan BB add port 12 untagged
    - configure vlan BB ipaddress 10.20.0.1/30
    - create vlan CONT tag 110
    - configure vlan CONT add port 11 untagged
    - configure vlan CONT ipaddress 10.20.0.9/30
    - enable ipforwarding vlan LCC
    - enable ipforwarding vlan LABARC
    - enable ipforwarding vlan LABSPI
    - enable ipforwarding vlan BB
    - enable ipforwarding vlan CONT
    route_commands:
    - configure iproute add 10.20.5.0/27 10.20.0.2
    - configure iproute add 10.20.5.64/27 10.20.0.2
  R2:
    host: 192.168.67.103
    port: 5002
    vlan_commands:
    - create vlan LAEG tag 10
    - configure vlan LAEG add port 1 untagged
    - configure vlan LAEG ipaddress 10.20.5.1/27
    - create vlan MAT tag 20
    - configure vlan MAT add port 2 untagged
    - configure vlan MAT ipaddress 10.20.5.65/28
    - create vlan LTD tag 30
    - configure vlan LTD add port 3 untagged
    - configure vlan LTD ipaddress 10.20.5.81/28
    - create vlan BB tag 120
    - configure vlan BB add port 12 untagged
    - configure vlan BB ipaddress 10.20.0.5/30
    - create vlan CONT tag 110
    - configure vlan CONT add port 11 untagged
    - configure vlan CONT ipaddress 10.20.0.10/30
    - enable ipforwarding vlan LAEG
    - enable ipforwarding vlan MAT
    - enable ipforwarding vlan LTD
    - enable ipforwarding vlan BB
    - enable ipforwarding vlan CONT
    route_commands:
    - configure iproute add 10.20.4.0/25 10.20.0.6
    - configure iproute add 10.20.4.224/28 10.20.0.6
  R3:
    host: 192.168.67.103
    port: 5004
    vlan_commands:
    - create vlan BB-R1 tag 10
    - configure vlan BB-R1 add port 1 untagged
    - configure vlan BB-R1 ipaddress 10.20.0.2/30
    - create vlan BB-R2 tag 20
    - configure vlan BB-R2 add port 2 untagged
    - configure vlan BB-R2 ipaddress 10.20.0.6/30
    - enable ipforwarding vlan BB-R1
    - enable ipforwarding vlan BB-R2
    route_commands:
    - configure iproute add 10.20.4.0/25 10.20.0.1
    - configure iproute add 10.20.4.224/28 10.20.0.1
    - configure iproute add 10.20.5.0/27 10.20.0.5
    - configure iproute add 10.20.5.64/27 10.20.0.5
